# Generated by Django 5.1.4 on 2025-01-14 22:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactoempresa',
            old_name='idEmpresa',
            new_name='empresa',
        ),
    ]
