# Generated by Django 5.1.4 on 2025-01-28 22:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0003_documento'),
    ]

    operations = [
        migrations.CreateModel(
            name='solicitudContacto',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('cargo', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('empresa', models.CharField(max_length=255)),
                ('pais', models.CharField(max_length=255)),
                ('mensaje', models.TextField()),
                ('origen', models.CharField(max_length=255)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
    ]
