# Generated by Django 5.1.4 on 2025-01-29 21:28

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0005_solicitudcontacto_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='pais',
            field=django_countries.fields.CountryField(max_length=2),
        ),
    ]
