# Generated by Django 5.1.4 on 2025-01-29 21:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0006_alter_empresa_pais'),
    ]

    operations = [
        migrations.AlterField(
            model_name='empresa',
            name='pais',
            field=models.CharField(max_length=255),
        ),
    ]
