# Generated by Django 5.1.4 on 2025-02-18 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0008_alter_documento_archivo'),
        ('desafios', '0012_alter_desafio_imagen'),
        ('iniciativas', '0008_alter_postulacioniniciativa_estado_iniciativa'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Metrica',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('valorInicial', models.IntegerField()),
                ('valorDeseado', models.IntegerField()),
                ('periodo', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('isActive', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('etapa', models.CharField(max_length=255)),
                ('estado', models.CharField(max_length=255)),
                ('isActive', models.BooleanField(default=True)),
                ('desafio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desafios.desafio')),
                ('ejecutivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('iniciativa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iniciativas.iniciativa')),
            ],
        ),
        migrations.CreateModel(
            name='Evaluacion',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('numero', models.IntegerField()),
                ('valor', models.IntegerField()),
                ('nota', models.TextField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('isActive', models.BooleanField(default=True)),
                ('metrica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.metrica')),
            ],
        ),
        migrations.CreateModel(
            name='Actividad',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('descripcion', models.TextField()),
                ('fechaCreacion', models.DateTimeField(auto_now_add=True)),
                ('fechaRealizado', models.DateTimeField()),
                ('estado', models.CharField(max_length=255)),
                ('responsable', models.CharField(max_length=255)),
                ('isActive', models.BooleanField(default=True)),
                ('metrica', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.metrica')),
            ],
        ),
        migrations.CreateModel(
            name='Objetivo',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('responsable', models.CharField(max_length=255)),
                ('fechaObjetivo', models.DateTimeField()),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('isActive', models.BooleanField(default=True)),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.match')),
            ],
        ),
        migrations.AddField(
            model_name='metrica',
            name='objetivo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.objetivo'),
        ),
    ]
