# Generated by Django 5.1.4 on 2025-02-26 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0009_metrica_match_evaluacion_actividad_objetivo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actividad',
            name='fechaRealizado',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
