# Generated by Django 5.1.4 on 2025-02-27 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0010_alter_actividad_fecharealizado'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='brl_trl',
            field=models.CharField(default='Opcion 1', max_length=255),
            preserve_default=False,
        ),
    ]
