# Generated by Django 5.1.4 on 2025-02-27 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0011_match_brl_trl'),
    ]

    operations = [
        migrations.AddField(
            model_name='objetivo',
            name='perspectiva',
            field=models.CharField(default='Financiera', max_length=255),
            preserve_default=False,
        ),
    ]
