# Generated by Django 5.1.4 on 2025-02-27 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0012_objetivo_perspectiva'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='brl_trl',
        ),
        migrations.AddField(
            model_name='match',
            name='brl',
            field=models.CharField(default='BRL 1', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='trl',
            field=models.CharField(default='TRL 1', max_length=255),
            preserve_default=False,
        ),
    ]
