# Generated by Django 5.1.4 on 2025-02-28 13:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0013_remove_match_brl_trl_match_brl_match_trl'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='match',
            name='etapa',
        ),
    ]
