# Generated by Django 5.1.4 on 2025-02-28 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0014_remove_match_etapa'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evaluacion',
            name='numero',
        ),
        migrations.AlterField(
            model_name='evaluacion',
            name='fecha',
            field=models.DateTimeField(),
        ),
    ]
