# Generated by Django 5.1.4 on 2025-04-30 00:22

import administracion.models
import django.core.files.storage
from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0015_remove_evaluacion_numero_alter_evaluacion_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(
                storage=django.core.files.storage.FileSystemStorage(location=settings.MEDIA_ROOT),
                upload_to=administracion.models.document_upload_path
            ),
        ),
    ]
