# Generated by Django 5.1.4 on 2025-05-07 02:19

import administracion.models
import django.core.files.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0016_alter_documento_archivo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactoempresa',
            name='empresa',
        ),
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='D:\\ua\\7mo semestre\\NODO\\NODOGrupo3\\administracion'), upload_to=administracion.models.document_upload_path),
        ),
        migrations.CreateModel(
            name='usuario_base',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('correo', models.CharField(max_length=255)),
                ('contraseña', models.EmailField(max_length=254)),
                ('rol', models.CharField(max_length=100)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('es_activo', models.BooleanField(default=True)),
                ('cargo', models.CharField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('empresa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='administracion.empresa')),
            ],
            options={
                'verbose_name': 'Usuario Base',
                'verbose_name_plural': 'Usuarios Base',
            },
        ),
    ]
