# Generated by Django 5.1.4 on 2025-05-07 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0017_remove_contactoempresa_empresa_and_more'),
        ('desafios', '0013_alter_desafio_contacto_and_more'),
        ('iniciativas', '0010_alter_iniciativa_contacto_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='contactoEmpresa',
        ),
    ]
