# Generated by Django 5.1.4 on 2025-05-17 02:09

import administracion.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0018_delete_contactoempresa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\angel.COSMICO\\OneDrive\\Documentos\\GitHub\\NODOGrupo3\\administracion'), upload_to=administracion.models.document_upload_path),
        ),
    ]
