# Generated by Django 5.1.4 on 2025-06-03 19:13

import administracion.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0021_alter_documento_archivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='documento',
            name='archivo',
            field=models.FileField(storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\benja\\OneDrive\\Escritorio\\NODO\\administracion'), upload_to=administracion.models.document_upload_path),
        ),
    ]
