# Generated by Django 5.1.4 on 2025-02-11 22:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0008_alter_documento_archivo'),
        ('desafios', '0012_alter_desafio_imagen'),
        ('iniciativas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulacioniniciativa',
            name='contacto',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administracion.contactoempresa'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postulacioniniciativa',
            name='empresa',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='administracion.empresa'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='postulacioniniciativa',
            name='desafio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='desafios.desafio'),
        ),
        migrations.AlterField(
            model_name='postulacioniniciativa',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
