# Generated by Django 5.1.4 on 2025-02-12 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iniciativas', '0002_postulacioniniciativa_contacto_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulacioniniciativa',
            name='diferenciacion',
            field=models.TextField(default='test', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postulacioniniciativa',
            name='latam',
            field=models.CharField(default='Si', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postulacioniniciativa',
            name='traccion',
            field=models.TextField(default='Test', max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='postulacioniniciativa',
            name='video',
            field=models.URLField(blank=True, max_length=255),
        ),
    ]
