# Generated by Django 5.1.4 on 2025-02-13 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iniciativas', '0003_postulacioniniciativa_diferenciacion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulacioniniciativa',
            name='piloto',
            field=models.TextField(default='no', max_length=255),
            preserve_default=False,
        ),
    ]
