# Generated by Django 5.1.4 on 2025-02-14 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iniciativas', '0004_postulacioniniciativa_piloto'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulacioniniciativa',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
