# Generated by Django 5.1.4 on 2025-02-14 03:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('iniciativas', '0005_postulacioniniciativa_isactive'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postulacioniniciativa',
            old_name='fecha_creacion',
            new_name='fecha',
        ),
    ]
