# Generated by Django 5.1.4 on 2025-02-14 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iniciativas', '0006_rename_fecha_creacion_postulacioniniciativa_fecha'),
    ]

    operations = [
        migrations.AddField(
            model_name='postulacioniniciativa',
            name='estado',
            field=models.CharField(default='Por depurar', max_length=255),
        ),
    ]
