# Generated by Django 5.1.4 on 2025-02-18 13:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0008_alter_documento_archivo'),
        ('desafios', '0012_alter_desafio_imagen'),
        ('iniciativas', '0007_postulacioniniciativa_estado'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulacioniniciativa',
            name='estado',
            field=models.CharField(default='Por Depurar', max_length=255),
        ),
        migrations.CreateModel(
            name='Iniciativa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('descripcion', models.TextField()),
                ('preevaluacion', models.TextField()),
                ('recomendacion', models.TextField()),
                ('madurez', models.CharField(max_length=255)),
                ('presentacion', models.FileField(blank=True, upload_to='')),
                ('comite', models.CharField(max_length=255)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('isActive', models.BooleanField(default=True)),
                ('contacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.contactoempresa')),
                ('desafio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desafios.desafio')),
                ('ejecutivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('empresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.empresa')),
                ('postulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='iniciativas.postulacioniniciativa')),
            ],
        ),
    ]
