# Generated by Django 5.1.4 on 2025-02-18 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('iniciativas', '0008_alter_postulacioniniciativa_estado_iniciativa'),
    ]

    operations = [
        migrations.AddField(
            model_name='iniciativa',
            name='titulo',
            field=models.CharField(default='titulo test', max_length=255),
            preserve_default=False,
        ),
    ]
