# Generated by Django 5.1.4 on 2025-05-07 02:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('administracion', '0017_remove_contactoempresa_empresa_and_more'),
        ('iniciativas', '0009_iniciativa_titulo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iniciativa',
            name='contacto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.usuario_base'),
        ),
        migrations.AlterField(
            model_name='postulacioniniciativa',
            name='contacto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='administracion.usuario_base'),
        ),
    ]
