# Generated by Django 5.1.4 on 2025-06-09 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('administracion', '0022_alter_documento_archivo'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoogleToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_token', models.TextField()),
                ('refresh_token', models.TextField(blank=True, null=True)),
                ('token_uri', models.CharField(default='https://oauth2.googleapis.com/token', max_length=255)),
                ('client_id', models.CharField(max_length=255)),
                ('client_secret', models.CharField(max_length=255)),
                ('scopes', models.TextField()),
                ('expiry', models.DateTimeField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='administracion.usuario_base')),
            ],
        ),
        migrations.CreateModel(
            name='SolicitudReunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('inicial', 'Reunión Inicial'), ('seguimiento', 'Seguimiento'), ('presentacion', 'Presentación de Solución'), ('evaluacion', 'Evaluación'), ('otra', 'Otra')], default='inicial', max_length=20, verbose_name='Tipo de reunión')),
                ('fecha_propuesta', models.DateTimeField(verbose_name='Fecha y hora propuesta')),
                ('duracion_propuesta', models.PositiveIntegerField(default=30, verbose_name='Duración propuesta (minutos)')),
                ('motivo', models.TextField(verbose_name='Motivo de la reunión')),
                ('estado', models.CharField(choices=[('pendiente', 'Pendiente'), ('aceptada', 'Aceptada'), ('rechazada', 'Rechazada'), ('cancelada', 'Cancelada')], default='pendiente', max_length=20, verbose_name='Estado de la solicitud')),
                ('invitados_adicionales', models.TextField(blank=True, help_text='Correos electrónicos separados por comas', verbose_name='Invitados adicionales')),
                ('creada_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizada_en', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('destinatario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_recibidas', to='administracion.usuario_base', verbose_name='Usuario destinatario')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_reunion', to='administracion.match', verbose_name='Match relacionado')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_enviadas', to='administracion.usuario_base', verbose_name='Usuario que solicita')),
            ],
            options={
                'verbose_name': 'Solicitud de Reunión',
                'verbose_name_plural': 'Solicitudes de Reunión',
                'ordering': ['-creada_en'],
                'permissions': [('puede_solicitar', 'Puede solicitar reuniones'), ('puede_responder', 'Puede responder a solicitudes')],
            },
        ),
        migrations.CreateModel(
            name='Reunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('inicial', 'Reunión Inicial'), ('seguimiento', 'Seguimiento'), ('presentacion', 'Presentación de Solución'), ('evaluacion', 'Evaluación'), ('otra', 'Otra')], default='inicial', max_length=20, verbose_name='Tipo de reunión')),
                ('fecha', models.DateTimeField(verbose_name='Fecha y hora')),
                ('duracion', models.PositiveIntegerField(help_text='Duración en minutos', verbose_name='Duración (minutos)')),
                ('motivo', models.TextField(verbose_name='Motivo de la reunión')),
                ('decisiones', models.TextField(blank=True, verbose_name='Decisiones tomadas')),
                ('link_meet', models.URLField(blank=True, null=True, verbose_name='Enlace Meet')),
                ('google_event_id', models.CharField(blank=True, max_length=255, null=True, verbose_name='ID Evento Google')),
                ('creada_en', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('actualizada_en', models.DateTimeField(auto_now=True, verbose_name='Última actualización')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reuniones', to='administracion.match', verbose_name='Match relacionado')),
                ('organizador', models.ForeignKey(limit_choices_to={'rol': 'ejecutivo'}, on_delete=django.db.models.deletion.CASCADE, related_name='reuniones_organizadas', to='administracion.usuario_base', verbose_name='Ejecutivo organizador')),
                ('solicitud_origen', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reuniones.solicitudreunion', verbose_name='Solicitud origen')),
            ],
            options={
                'verbose_name': 'Reunión',
                'verbose_name_plural': 'Reuniones',
                'ordering': ['-fecha'],
                'permissions': [('puede_agendar', 'Puede agendar reuniones'), ('puede_invitar_externos', 'Puede invitar participantes externos')],
            },
        ),
        migrations.CreateModel(
            name='ParticipanteReunion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo electrónico')),
                ('nombre', models.CharField(blank=True, max_length=255, verbose_name='Nombre completo')),
                ('asistio', models.BooleanField(default=False, verbose_name='Confirmó asistencia')),
                ('es_invitado_externo', models.BooleanField(default=False, verbose_name='Es invitado externo?')),
                ('notificado', models.BooleanField(default=False, verbose_name='Fue notificado?')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='administracion.usuario_base', verbose_name='Usuario registrado')),
                ('reunion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='reuniones.reunion', verbose_name='Reunión')),
            ],
            options={
                'verbose_name': 'Participante de Reunión',
                'verbose_name_plural': 'Participantes de Reuniones',
                'ordering': ['-es_invitado_externo', 'nombre'],
                'unique_together': {('reunion', 'email')},
            },
        ),
    ]
