# Generated by Django 5.1.4 on 2025-06-20 02:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reuniones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='googletoken',
            name='client_id',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='googletoken',
            name='client_secret',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='googletoken',
            name='expiry',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='googletoken',
            name='refresh_token',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='googletoken',
            name='token_uri',
            field=models.CharField(max_length=200),
        ),
    ]
