# Generated by Django 5.1.4 on 2025-01-23 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_post_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='portada',
            field=models.ImageField(default='no image', upload_to='django-summernote/portadas/'),
        ),
    ]
