# Generated by Django 5.1.4 on 2025-01-23 12:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_portada'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='portada',
            field=models.ImageField(blank=True, default='django-summernote/portadas/default.png', upload_to='django-summernote/portadas/'),
        ),
    ]
