# Generated by Django 5.1.4 on 2025-01-23 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_post_portada'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='tags',
            field=models.CharField(blank=True, help_text='Agrega tags separados por comas ', max_length=255),
        ),
    ]
