# Generated by Django 5.1.4 on 2025-01-24 00:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, help_text='Este sera el nombre del enlace para ver el post <br>  *Dejalo vacio si quieres que sea el nombre del post',),
        ),
    ]
