# Generated by Django 5.1.4 on 2025-01-25 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_post_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='slug',
            field=models.SlugField(blank=True, help_text='Este sera el nombre del enlace para ver el post <br>  *Dejalo vacio si quieres que sea el nombre del post', max_length=200),
        ),
    ]
