# Generated by Django 5.1.4 on 2025-03-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_rename_content_post_contenido_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='publico',
            field=models.BooleanField(default=False),
        ),
    ]
