# Generated by Django 5.1.4 on 2025-01-06 18:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('cantPersonas', models.IntegerField()),
                ('año', models.IntegerField()),
                ('actividad', models.CharField(max_length=255)),
                ('pais', models.CharField(max_length=255)),
                ('ciudad', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='contactoEmpresa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=255)),
                ('cargo', models.CharField(max_length=255)),
                ('correo', models.EmailField(max_length=255)),
                ('telefono', models.CharField(max_length=20)),
                ('idEmpresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desafios.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='PostulacionDesafio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('descripcionInicial', models.TextField()),
                ('desafioFrase', models.TextField()),
                ('presupuesto', models.DecimalField(decimal_places=2, max_digits=15)),
                ('pregunta', models.TextField()),
                ('origen', models.CharField(max_length=255)),
                ('estado', models.CharField(default=False)),
                ('idContacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desafios.contactoempresa')),
                ('idEmpresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desafios.empresa')),
            ],
        ),
        migrations.CreateModel(
            name='Desafio',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('webEmpresa', models.URLField(blank=True, max_length=255)),
                ('nombreDesafio', models.CharField(max_length=255)),
                ('impactoProblema', models.TextField(blank=True)),
                ('efectoOperacion', models.TextField(blank=True)),
                ('descripcionDesafio', models.TextField(blank=True)),
                ('costoOportunidad', models.DecimalField(blank=True, decimal_places=2, max_digits=15)),
                ('intentosPreviosSolucion', models.TextField(blank=True)),
                ('documentacionProblema', models.TextField(blank=True)),
                ('ventasMesUsd', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('margenBruto', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('ebitda', models.DecimalField(decimal_places=2, max_digits=15, null=True)),
                ('cantidadClientes', models.IntegerField(null=True)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='Desafios/')),
                ('isPrincipal', models.BooleanField(default=False)),
                ('show', models.BooleanField(default=False)),
                ('idContacto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desafios.contactoempresa')),
                ('idEjecutivo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('idEmpresa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desafios.empresa')),
                ('idPostulacion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='desafios.postulaciondesafio')),
            ],
        ),
    ]
