# Generated by Django 5.1.4 on 2025-01-06 18:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafios', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulaciondesafio',
            name='estado',
            field=models.BooleanField(default=False),
        ),
    ]
