# Generated by Django 5.1.4 on 2025-01-07 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafios', '0002_alter_postulaciondesafio_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulaciondesafio',
            name='estado',
            field=models.CharField(default=False),
        ),
    ]
