# Generated by Django 5.1.4 on 2025-01-08 02:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafios', '0003_alter_postulaciondesafio_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulaciondesafio',
            name='presupuesto',
            field=models.CharField(max_length=255),
        ),
    ]
