# Generated by Django 5.1.4 on 2025-01-13 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafios', '0004_alter_postulaciondesafio_presupuesto'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactoempresa',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='desafio',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='empresa',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='postulaciondesafio',
            name='isActive',
            field=models.BooleanField(default=True),
        ),
    ]
