# Generated by Django 5.1.4 on 2025-01-13 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafios', '0005_contactoempresa_isactive_desafio_isactive_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postulaciondesafio',
            name='estado',
            field=models.CharField(default='Por Depurar'),
        ),
    ]
