# Generated by Django 5.1.4 on 2025-01-14 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafios', '0006_alter_postulaciondesafio_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desafio',
            name='descripcionDesafio',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
