# Generated by Django 5.1.4 on 2025-01-14 22:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafios', '0008_alter_desafio_idcontacto_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='desafio',
            old_name='idContacto',
            new_name='contacto',
        ),
        migrations.RenameField(
            model_name='desafio',
            old_name='idEjecutivo',
            new_name='ejecutivo',
        ),
        migrations.RenameField(
            model_name='desafio',
            old_name='idEmpresa',
            new_name='empresa',
        ),
        migrations.RenameField(
            model_name='desafio',
            old_name='idPostulacion',
            new_name='postulacion',
        ),
        migrations.AlterField(
            model_name='desafio',
            name='documentacionProblema',
            field=models.FileField(blank=True, max_length=255, upload_to=''),
        ),
    ]
