# Generated by Django 5.1.4 on 2025-01-14 23:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desafios', '0009_rename_idcontacto_desafio_contacto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desafio',
            name='documentacionProblema',
        ),
    ]
