# Generated by Django 5.1.4 on 2025-01-14 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('desafios', '0010_remove_desafio_documentacionproblema'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postulaciondesafio',
            old_name='idContacto',
            new_name='contacto',
        ),
        migrations.RenameField(
            model_name='postulaciondesafio',
            old_name='idEmpresa',
            new_name='empresa',
        ),
    ]
