# Generated by Django 5.1.4 on 2025-02-11 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('desafios', '0011_rename_idcontacto_postulaciondesafio_contacto_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='desafio',
            name='imagen',
            field=models.ImageField(default='Desafios/default.jpg', upload_to='Desafios/'),
        ),
    ]
